export const BASE_URL_SIGNIN =
  'https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=';
export const BASE_URL_SIGNUP =
  'https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=';
export const BASE_URL_GET_USER =
  'https://identitytoolkit.googleapis.com/v1/accounts:createAuthUri?key=';
export const USER_PATTERN = '[a-zA-Z -]*';
export const INVALID_EMAIL = 'INVALID_EMAIL';
export const INVALID_PASSWORD = 'INVALID_PASSWORD';
export const EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND';
